name: CI Pipeline with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Construire l'image Docker
      run: docker build -t demo-devops-app .
    
    - name: Lancer des tests
      run: |
        # Test sur port 8081 pour éviter conflits
        docker run -d --name test-app -p 8081:80 demo-devops-app
        sleep 5
        
        # Vérifie que le conteneur tourne
        if docker ps | grep -q test-app; then
          echo "✅ Conteneur démarré avec succès"
          
          # Test HTTP rapide
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081 || echo "000")
          if [ "$STATUS_CODE" = "200" ]; then
            echo "✅ Site accessible (HTTP 200)"
          else
            echo "⚠️  Code HTTP: $STATUS_CODE"
          fi
        else
          echo "❌ Conteneur non démarré"
          exit 1
        fi
        
        # Nettoyage
        docker stop test-app
        docker rm test-app
    
    - name: Scan de sécurité (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'demo-devops-app'
        format: 'table'
        exit-code: '0' 
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'  
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Construire et pousser vers GHCR
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/demo-devops-app:latest
          ghcr.io/${{ github.repository_owner }}/demo-devops-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Déployer sur GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./