name: 🐳 CI Pipeline with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: docker build -t demo-devops-app .
    
    - name: Run tests
      run: |
        docker run --rm demo-devops-app echo "Construction réussie !"
        # Add real tests here
    
    - name: Security scan (Trivy)
      continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'demo-devops-app'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/demo-devops-app:latest
          ${{ secrets.DOCKER_USERNAME }}/demo-devops-app:${{ github.sha }}
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./